### PR TITLE
work around mpconfig dropping support for empty array

### LINKED ISSUE #160: MP Config - introduce constant for empty string
Currently we allow users to set their defaults via MP config in the following way - `ThreadContext/propagated=`.
This is interpreted as "no contexts are to be propagated".

Now, looking at the changes proposed in https://github.com/eclipse/microprofile-config/issues/397 and the respective PR https://github.com/eclipse/microprofile-config/pull/407, we are going to have to change this.
With the above, empty value means you won't be able to see the key is there at all.

Hence I would suggest some constant, much like we have the `REMAINING` one, but this one would have to be something like `none`?

What do you guys think?

### PR DESCRIPTION
**Pull request by njr-11**
contains most of the fix for #160

### CODE REVIEW

**Review by Emily-Jiang — APPROVED** [review]
LGTM!

**Review by manovotn — APPROVED** [review]
Sorry for the delay, was on PTO.
This is fine with me.

**Review by FroMage — APPROVED** [review]
LGTM, but should we forbid `ThreadContextProvider` with the name `None` to be extra sure we'll never run into issues? I guess MP config will always filter them out, but still…

**Comment by njr-11** [comment]
> LGTM, but should we forbid `ThreadContextProvider` with the name `None` to be extra sure we'll never run into issues? I guess MP config will always filter them out, but still…

It seems extremely unlikely that anyone would name their ThreadContextProvider "None", but it's easy enough to explicitly forbid that so we might as well.  I'll add it in a separate pull under the same issue given that there are already 3 approvals on this one.

**Pull request merged**
